version: '3.7'
services:

  php-fpm:
    image: ${REGISTRY}/${INDEX}-php-fpm:${IMAGE_TAG}
    environment:
      ENV: ${ENV}
      RENDER_MODE: ${RENDER_MODE}
      API_AUTH_KEY: ${API_AUTH_KEY}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./:/var/www/html

  php-cli:
    image: ${REGISTRY}/${INDEX}-php-cli:${IMAGE_TAG}
    environment:
      ENV: ${ENV}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./:/app

  nginx:
    image: ${REGISTRY}/${INDEX}-nginx:${IMAGE_TAG}
    ports:
      - ${APP_WEB_PORT}:80
    volumes:
      - ./:/var/www/html

  mariadb:
    image: mariadb:10.6.14
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']

volumes:
  mysql: